vim.opt_local.formatoptions:remove({ 'r', 'o' })
vim.api.nvim_buf_set_keymap(0, 'i', '"', "'", { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', "'", '"', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'n', 't"', "r'", { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'n', "t'", 'r"', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', 'qt', '-- TODO: ', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', 'qp', 'vim.notify()<Left>', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', 'qP', 'vim.notify(vim.inspect())<Left><Left>', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', 'qfp', 'vim.notify(tostring())<Left><Left>', { noremap = true })
